use_frameworks!

platform :ios, '8.0'

target 'ASFoundation_Example' do
  pod 'ASFoundation', :path => '../'

  target 'ASFoundation_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
